server:
  port: 8082
spring:
  application:
    name: notification

  zipkin:
    base-url: http://localhost:9411

  datasource:
    username: 'admin'
    password: 'userpass'
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


rabbitmq :
  exchanges:
    internal: internal-exchange
  queue :
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
